train_dataset: FC100
train_dataset_args: {split: train, augment: resize}
val_dataset: FC100
val_dataset_args: {split: trainval}
fs_dataset: FC100
fs_dataset_args: {split: test}
eval_fs_epoch: 5

model: classifier
model_args:
    encoder: resnet50
    encoder_args: {}
    classifier: linear-classifier 
    classifier_args: {n_classes: 80}  # train dataset contains 60 classes, in_dim: 512
load_encoder: ./weight/resnet50/best_epoch.pth

lr: 0.1

batch_size: 256
max_epoch: 200
optimizer: sgd
optimizer_args: {lr: 0.1, weight_decay: 5.e-4, milestones: [160,180]}

save_epoch: 30
visualize_datasets: true


