# train_dataset: FC100
# train_dataset_args: {split: train, augment: flip}
# val_dataset: FC100
# val_dataset_args: {split: trainval}
# fs_dataset: FC100
# fs_dataset_args: {split: test}
# eval_fs_epoch: 5


train_dataset: FC100
train_dataset_args: {split: train}
tval_dataset: FC100
tval_dataset_args: {split: trainval}
val_dataset: FC100
val_dataset_args: {split: val}

model: meta-baseline
model_args: 
    encoder: vit_base_patch16_224_in21k
    encoder_args: {}
load_encoder: /home/wzp/few-shot-meta-baseline/checkpoint/fc100/jx_vit_base_patch16_224_in21k-e5005f0a.pth

n_way: 5
n_shot: 1
n_query: 15
train_batches: 200
ep_per_batch: 4

max_epoch: 20
optimizer: sgd
optimizer_args: {lr: 0.001, weight_decay: 5.e-4}

visualize_datasets: True
