train_dataset: FC100
train_dataset_args: {split: train, augment: flip}
val_dataset: FC100
val_dataset_args: {split: trainval}
fs_dataset: FC100
fs_dataset_args: {split: test}
eval_fs_epoch: 5

model: classifier
model_args:
    encoder: vit_base_patch16_224_in21k
    encoder_args: {}
    classifier: linear-classifier 
    classifier_args: {n_classes: 80}  # train dataset contains 60 classes, in_dim: 512
load_encoder: /home/wzp/few-shot-meta-baseline/checkpoint/fc100/jx_vit_base_patch16_224_in21k-e5005f0a.pth

lr: 0.002

batch_size: 512
max_epoch: 200
optimizer: sgd
optimizer_args: {lr: 0.1, weight_decay: 5.e-4, milestones: [180]}

save_epoch: 5
visualize_datasets: true
